[project]
name = "undate-notebook-usrse25"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.2",
    "undate>=0.5.2",
    "altair>=5.5.0",
    "marimo>=0.16.5",
    "ruff>=0.12.11",
    "polars>=1.32.3",
    "pandas>=2.3.2",
    "dplib-py[polars]>=1.1.0",
    "datapackage>=1.15.4",
    "pyarrow>=21.0.0",
]

[tool.marimo.display]
custom_css = ["local.css"]