[project]
name = "undate-notebook-usrse25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.2",
    "undate>=0.4.0",
    "pandas>=2.2.3",
    "altair>=5.5.0"
]
